### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (128,) (127,) (128,)

### ISSUE THREAD

**Issue by Nidachuhan** [zhangmeishan/BiaffineDParser#3]
I run this on python 3.7 , Pytorch version 1.1.0
when I run the python driver/TrainTest.py --config_file config.ctb51.cfg I found this error 
please resolve this thanks 
Traceback (most recent call last):
  File "driver/TrainTest.py", line 149, in <module>
    vec = vocab.load_pretrained_embs(config.pretrained_embeddings_file)
  File ".\data\Vocab.py", line 60, in load_pretrained_embs
    embeddings[self.UNK] += vector
ValueError: operands could not be broadcast together with shapes (128,) (127,) (128,)

**Comment by WUT-Post** [comment]
I have same problems 

Loaded config file sucessfully.
pretrained_embeddings_file experiments/ctb51/giga.txt
data_dir experiments/ctb51
train_file experiments/ctb51/zh-ud-train.conllu
dev_file experiments/ctb51/zh-ud-dev.conllu
test_file experiments/ctb51/zh-ud-test.conllu
min_occur_count 2
save_dir experiments/ctb51_model
config_file experiments/ctb51_model/config.cfg
save_model_path experiments/ctb51_model/model
save_vocab_path experiments/ctb51_model/vocab
load_dir ../ckpt/default
load_model_path ../ckpt/default/model
load_vocab_path ../ckpt/default/vocab
lstm_layers 3
word_dims 128
tag_dims 128
dropout_emb 0.33
lstm_hiddens 400
dropout_lstm_input 0.33
dropout_lstm_hidden 0.33
mlp_arc_size 500
mlp_rel_size 100
dropout_mlp 0.33
learning_rate 2e-3
decay .75
decay_steps 5000
beta_1 .9
beta_2 .9
epsilon 1e-12
clip 5.0
num_buckets_train 40
num_buckets_valid 10
num_buckets_test 10
train_iters 50000
train_batch_size 50
test_batch_size 128
validate_every 165
save_after 5000
update_every 4
Total num:  3997
Proj num:  3975
Vocab info: #words 4424, #tags 17, #rels 43
Total words: 42422

The dim of pretrained embeddings: 128

Traceback (most recent call last):
  File "driver/TrainTest.py", line 149, in <module>
    vec = vocab.load_pretrained_embs(config.pretrained_embeddings_file)
  File ".\data\Vocab.py", line 60, in load_pretrained_embs
    embeddings[self.UNK] += vector
ValueError: operands could not be broadcast together with shapes (128,) (127,) (128,)

**Comment by HongyanJiao** [comment]
I have the same problem
The dim of pretrained embeddings: 100

Traceback (most recent call last):
  File "driver/TrainTest.py", line 150, in <module>
    vec = vocab.load_pretrained_embs(config.pretrained_embeddings_file)
  File "./data/Vocab.py", line 60, in load_pretrained_embs
    embeddings[self.UNK] += vector
ValueError: operands could not be broadcast together with shapes (100,) (99,) (100,)
